sudo: required
services: 
  - docker

before_install:
  - docker build -t keegang/docker-react -f Dockerfile.dev .

script:
  - docker run keegang/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-657633822694"
  bucket_path: "docker-react"
  on:
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"